# Generated by Django 4.1.1 on 2022-09-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(max_length=254)),
                ('total_subscribers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DayEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('data', models.DateField()),
                ('emails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='email_app.email')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='email_app.subscribers')),
            ],
        ),
    ]
