# Generated by Django 4.1.1 on 2022-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_subscribers_dayedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='total_subscribers',
            field=models.IntegerField(blank=True),
        ),
    ]
