# Generated by Django 4.1.1 on 2022-09-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0004_remove_subscribers_total_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='total_subscribers',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
