# Generated by Django 4.1.1 on 2022-09-12 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_subscribers_total_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='total_subscribers',
        ),
    ]
